import "./globals.scss";
import { Unbounded, Volkhov } from "next/font/google";
import { NavBar } from "./components/NavBar";

const unbounded = Unbounded({
  subsets: ["latin"],
  variable: "--font-unbounded",
});

const volkhov = Volkhov({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
  variable: "--font-volkhov",
});

export const metadata = {
  title: "Lincoln High School Class of 1973 50th Reunion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${volkhov.className} ${unbounded.variable} ${volkhov.variable}`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
